### ISSUE TITLE
Add `Code .` to suggested commands

### ISSUE THREAD

**Issue by lizthrilla** [suncoast-devs/app-app#8]
When app-app is finished it suggests to `cd` into the project and type `yarn start`. 

Could we add `Code .` in between those two suggestions?  That is something I have noticed that part time students struggle with remembering at first.

**Comment by DylanAttal** [comment]
PR submitted 😄 https://github.com/suncoast-devs/app-app/pull/9

**Comment by ambethia** [comment]
Closed in #9
